<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>TheSpark.HardwareMonitor.Platform.Windows</RootNamespace>
    <AssemblyName>TheSpark.HardwareMonitor.Platform.Windows</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" />
  </ItemGroup>
</Project>
