<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>TheSpark.HardwareMonitor.Core.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\HardwareMonitor.Core\HardwareMonitor.Core.csproj" />
    <ProjectReference Include="..\..\src\HardwareMonitor.Diagnostics\HardwareMonitor.Diagnostics.csproj" />
  </ItemGroup>
</Project>
